import type { Level } from './types';

export const misinformationLevels: Level[] = [
    {
        id: 'misinfo-1',
        worldId: 'misinformation',
        number: 1,
        title: 'The News Feed',
        subtitle: 'Real or fake?',
        intro: [
            { text: "The internet is full of real news… and not-so-real news. Sometimes it's hard to tell the difference." },
            { text: "Let's practice. I'll show you posts — swipe RIGHT if it looks real, LEFT if it looks fake." },
        ],
        challenge: {
            type: 'swipe',
            instruction: 'Is this post real news or misinformation?',
            labelRight: 'REAL',
            labelLeft: 'FAKE',
            items: [
                {
                    id: 's1',
                    post: {
                        username: 'Daily Science',
                        handle: '@dailyscience',
                        avatar: '🔬',
                        content: 'Scientists have discovered a new species of deep-sea fish with bioluminescent patterns near the Mariana Trench. Full study published in Nature.',
                        time: '1h ago',
                        likes: 2840,
                        reposts: 445,
                        verified: true,
                    },
                    isReal: true,
                    explanation: "✅ Real. Verified account, specific factual claim, references a real journal. This is how credible science reporting looks.",
                },
                {
                    id: 's2',
                    post: {
                        username: 'TRUTH REVEALER',
                        handle: '@wakeup_sheeple99',
                        avatar: '⚠️',
                        content: 'DOCTORS DON\'T WANT YOU TO KNOW: Drinking lemon water CURES cancer!! Big pharma is hiding this!! SHARE BEFORE DELETED 🚨🚨🚨',
                        time: '3h ago',
                        likes: 15203,
                        reposts: 8421,
                    },
                    isReal: false,
                    explanation: "❌ Fake. All-caps urgency, 'they don't want you to know', no source, no verification, and a dangerous medical false claim. Classic misinformation.",
                },
                {
                    id: 's3',
                    post: {
                        username: 'ABC News',
                        handle: '@ABCnews',
                        avatar: '📺',
                        content: 'Local flooding in Far North Queensland prompts evacuation orders for 2,000 residents. QLD Fire & Emergency Services urge residents to follow all official warnings.',
                        time: '30 min ago',
                        likes: 1102,
                        reposts: 289,
                        verified: true,
                    },
                    isReal: true,
                    explanation: "✅ Real. Verified news outlet, specific details (location, numbers), references official emergency services.",
                },
                {
                    id: 's4',
                    post: {
                        username: 'CryptoKinggg',
                        handle: '@cryptoking999',
                        avatar: '💰',
                        content: 'Breaking: Elon Musk PERSONALLY told me Bitcoin will hit $1,000,000 by Tuesday. Load up NOW or regret it forever 🚀🚀 I got the screenshot',
                        time: '2h ago',
                        likes: 34500,
                        reposts: 12800,
                    },
                    isReal: false,
                    explanation: "❌ Fake. Unverifiable 'screenshot', impossible financial claim, high-pressure urgency, no verification. Likely a pump-and-dump scam.",
                },
                {
                    id: 's5',
                    post: {
                        username: 'ScienceAlert',
                        handle: '@ScienceAlert',
                        avatar: '🧪',
                        content: 'New Stanford research suggests 30 minutes of daily walking correlates with reduced anxiety in adults. The study tracked 12,000 participants over 3 years.',
                        time: '5h ago',
                        likes: 8933,
                        reposts: 1240,
                        verified: true,
                    },
                    isReal: true,
                    explanation: "✅ Real. Named institution, hedged language ('suggests', 'correlates'), specific study details, verified account. This is good science journalism.",
                },
            ],
        },
        lesson: "Look for: verified accounts, specific sources, hedged language ('suggests', 'may'). Be wary of all-caps urgency, 'share before deleted', and unverifiable claims.",
        successMessage: "You've got a good eye for misinformation!",
    },
    {
        id: 'misinfo-2',
        worldId: 'misinformation',
        number: 2,
        title: 'Before You Share',
        subtitle: 'Think before you hit send.',
        intro: [
            { text: "Your friend just sent you a wild post in a group chat: 'OMG did you see this?? This is insane!'" },
            { text: "What do you do before sharing it with everyone you know?" },
        ],
        challenge: {
            type: 'choice',
            situation: "Your friend sent this post to your group chat with 'OMG share this NOW!'. What do you do?",
            post: {
                username: 'Breaking Alert',
                handle: '@breaking_alert_99',
                avatar: '🚨',
                content: 'BREAKING: Government just announced all schools will close PERMANENTLY next month. Parents are FURIOUS. Share this immediately before it gets removed!!',
                time: '15 min ago',
                likes: 45000,
                reposts: 31000,
            },
            options: [
                {
                    id: 'a',
                    text: 'Forward it to everyone — this sounds serious!',
                    correct: false,
                    outcome: "You just spread unverified information to dozens of people. 'Share before it gets removed' is a classic manipulation tactic designed to short-circuit your critical thinking. 😬",
                },
                {
                    id: 'b',
                    text: 'Search for it on actual news sites first',
                    correct: true,
                    outcome: "Smart! Real news about school closures would be all over the ABC, Guardian, and government sites. If you can't find it anywhere else, it's almost certainly false. ✅",
                },
                {
                    id: 'c',
                    text: 'Ignore it — not my problem',
                    correct: false,
                    outcome: "Better than sharing it, but your friend is spreading misinformation. A gentle 'hey I couldn't find this anywhere, might want to check before sharing' goes a long way.",
                },
                {
                    id: 'd',
                    text: 'Comment \'This is fake news lol\' without checking',
                    correct: false,
                    outcome: "Without actually checking yourself, you're just guessing. Calling something fake without evidence is its own form of misinformation.",
                },
            ],
        },
        lesson: "Before sharing anything alarming, check: Is the account verified? Can you find it on a reputable news site? Does it use urgency language like 'share before deleted'? One 'yes' = be suspicious.",
        successMessage: "You stopped misinformation in its tracks.",
    },
    {
        id: 'misinfo-3',
        worldId: 'misinformation',
        number: 3,
        title: 'The Share Checklist',
        subtitle: 'Good habits before hitting share.',
        intro: [
            { text: "Now you know why checking matters — let's build the habit." },
            { text: "Here's your pre-share checklist. Which habits should you have turned ON?" },
        ],
        challenge: {
            type: 'configure',
            platform: 'Pre-Share Habits',
            context: "You found an interesting post you want to share. Which of these good habits should be active before you hit share?",
            settings: [
                {
                    id: 'check_verified',
                    label: 'Check if the account is verified',
                    description: 'Look for a verified badge or check their profile history',
                    value: false,
                    correctValue: true,
                    explanation: 'Verified accounts are less likely to post misinformation — though not impossible. Always a good first check.',
                },
                {
                    id: 'cross_reference',
                    label: 'Search for the story on other news sites',
                    description: 'Look for the same story reported by multiple reliable sources',
                    value: false,
                    correctValue: true,
                    explanation: 'Real news appears in multiple places. If only one account has the story, be suspicious.',
                },
                {
                    id: 'check_date',
                    label: 'Check the original publication date',
                    description: 'Old stories sometimes resurface and get shared as "breaking news"',
                    value: false,
                    correctValue: true,
                    explanation: 'A 3-year-old story shared as "breaking news" today is misleading, even if the original story was real.',
                },
                {
                    id: 'share_headline_only',
                    label: 'Share from the headline without reading the article',
                    description: 'Just read the headline and hit share',
                    value: true,
                    correctValue: false,
                    explanation: 'Headlines are written to get clicks, not to be accurate. The article often says something more nuanced — or even the opposite.',
                },
            ],
        },
        lesson: "Before sharing: verify the source, cross-reference the story, check the date, and read the full article — not just the headline.",
        successMessage: "You're a responsible sharer now!",
    },
];
