import type { Level } from './types';

export const phishingLevels: Level[] = [
    {
        id: 'phishing-1',
        worldId: 'phishing',
        number: 1,
        title: 'The Urgent DM',
        subtitle: "Something feels off…",
        intro: [
            { text: "You just got a DM. The sender looks official, and it says your account will be deleted if you don't click a link… right now." },
            { text: "Let's think carefully before doing anything." },
        ],
        challenge: {
            type: 'choice',
            situation: "You received this DM. What do you do?",
            post: {
                username: 'Quacky Official Support',
                handle: '@QuackySupport_Help2024',
                avatar: '🦆',
                content: '🚨 URGENT: Your account has been flagged for suspicious activity. Click immediately to verify or your account will be DELETED in 24 hours: bit.ly/quacky-verify-now',
                time: 'just now',
                likes: 0,
                reposts: 0,
            },
            options: [
                {
                    id: 'a',
                    text: "Click the link immediately — I don't want to lose my account!",
                    correct: false,
                    outcome: "That was a phishing link. Hackers now have your login. Real platforms never send account security alerts through DMs with random short links. 🚫",
                },
                {
                    id: 'b',
                    text: 'Reply asking for more information',
                    correct: false,
                    outcome: "Replying confirms your account is active and that you're engaging. This often leads to more manipulation attempts. Don't engage.",
                },
                {
                    id: 'c',
                    text: 'Report the account and check your settings directly in the app',
                    correct: true,
                    outcome: "Exactly right. Legitimate platforms never ask you to click a DM link to verify your account. You always go directly to official settings yourself. ✅",
                },
                {
                    id: 'd',
                    text: 'Ask your friends if they got the same message',
                    correct: false,
                    outcome: "Better than clicking, but you should report it first. Your friends won't know if it's fake — and chatting about it wastes time while the threat is active.",
                },
            ],
        },
        lesson: "Legitimate services NEVER ask you to click a link in a DM to verify your account. When in doubt, go directly to the app's official settings page yourself — never through a link someone sent you.",
        successMessage: "You spotted the phishing attempt. Nice work!",
    },
    {
        id: 'phishing-2',
        worldId: 'phishing',
        number: 2,
        title: 'The Giveaway',
        subtitle: 'Too good to be true?',
        intro: [
            { text: "Free iPhone! $1000 prize! Just follow, like, and DM us your details!" },
            { text: "You've probably seen these on your feed. Let's figure out what's really going on." },
        ],
        challenge: {
            type: 'choice',
            situation: "You see this post on your feed. What do you do?",
            post: {
                username: 'FREE iPHONE 16 GIVEAWAY 🎁',
                handle: '@iphone16_giveaway_official',
                avatar: '📱',
                content: 'Giving away 10 iPhone 16 Pro Max! TO ENTER: 1️⃣ Follow this account 2️⃣ Like this post 3️⃣ DM us your full name, home address, and date of birth! Winner announced Friday 🎉',
                time: '45 min ago',
                likes: 12400,
                reposts: 8900,
            },
            options: [
                {
                    id: 'a',
                    text: 'Follow, like, and DM them your details',
                    correct: false,
                    outcome: "You just sent your full name, home address, and date of birth to a stranger. This is a data-harvesting scam — that information can be used for identity theft. 😨",
                },
                {
                    id: 'b',
                    text: 'Just follow and like, skip sending details',
                    correct: false,
                    outcome: "You're not at immediate risk, but you've boosted a scam account's reach to others who might fall for it. Following scam accounts also gives them credibility.",
                },
                {
                    id: 'c',
                    text: 'Scroll past and report the account as a scam',
                    correct: true,
                    outcome: "Smart. Real giveaways never need your home address or date of birth via DM. Reporting protects other users from falling for it too. ✅",
                },
                {
                    id: 'd',
                    text: 'Share it with friends so they can enter',
                    correct: false,
                    outcome: "Now your friends might fall for the scam. Real prize contests run by brands never ask for your address via DM.",
                },
            ],
        },
        lesson: "Legitimate giveaways never ask for your address, date of birth, or personal details in a DM. If entry requires personal info beyond your username, it's a scam.",
        successMessage: "You didn't fall for it. Your data is safe!",
    },
    {
        id: 'phishing-3',
        worldId: 'phishing',
        number: 3,
        title: 'The Link Check',
        subtitle: 'Safe or sketchy?',
        intro: [
            { text: "Not all links are dangerous — but some look safe and aren't." },
            { text: "Swipe RIGHT if the link looks safe. Swipe LEFT if it's sketchy." },
        ],
        challenge: {
            type: 'swipe',
            instruction: 'Does this link look safe to click?',
            labelRight: 'SAFE',
            labelLeft: 'SKETCHY',
            items: [
                {
                    id: 'l1',
                    post: {
                        username: 'Northside High School',
                        handle: '@northside_hs',
                        avatar: '🏫',
                        content: 'Updated timetable for Term 3 is live! northsidehigh.edu.au/timetable',
                        time: 'Today',
                        likes: 45,
                        reposts: 12,
                    },
                    isReal: true,
                    explanation: "✅ Safe. Official school domain (.edu.au), posted from the school's own account. This is a trusted link.",
                },
                {
                    id: 'l2',
                    post: {
                        username: 'Netflix',
                        handle: '@netflix_prizes2024',
                        avatar: '🎬',
                        content: 'Congrats! Your account has been chosen for a FREE 1-year subscription. Claim it now before it expires: netflix-free-2024.xyz/claim',
                        time: '1h ago',
                        likes: 5600,
                        reposts: 2100,
                    },
                    isReal: false,
                    explanation: "❌ Sketchy. The handle isn't Netflix's real account, and the domain (netflix-free-2024.xyz) is not netflix.com. This is a phishing site that will steal your login.",
                },
                {
                    id: 'l3',
                    post: {
                        username: 'Spotify Australia',
                        handle: '@SpotifyAU',
                        avatar: '🎵',
                        content: 'New Australian playlist just dropped! 🎶 open.spotify.com/playlist/4uJ2...',
                        time: '3h ago',
                        likes: 8920,
                        reposts: 1445,
                        verified: true,
                    },
                    isReal: true,
                    explanation: "✅ Safe. Verified account, and the link domain is open.spotify.com — Spotify's real domain. Safe to click.",
                },
                {
                    id: 'l4',
                    post: {
                        username: 'Urgent Prize Alert',
                        handle: '@prize.winner.2024',
                        avatar: '🎁',
                        content: "You've won a $500 Amazon voucher! Collect in 24 hrs or it expires: amaz0n-voucher.net/collect?id=winner",
                        time: 'just now',
                        likes: 2,
                        reposts: 0,
                    },
                    isReal: false,
                    explanation: "❌ Sketchy. The domain uses 'amaz0n' (zero instead of 'o') — not amazon.com. Artificial urgency, almost zero engagement, and an account with a suspicious name.",
                },
            ],
        },
        lesson: "Always check the domain in a link: does it match the real site? Is it .com.au or .edu.au vs a random .xyz or .net? When in doubt, search for the real site directly rather than clicking.",
        successMessage: "Your link radar is sharp!",
    },
];
