import type { Level } from './types';

export const privacyLevels: Level[] = [
    {
        id: 'privacy-1',
        worldId: 'privacy',
        number: 1,
        title: 'The New Profile',
        subtitle: 'What goes public?',
        intro: [
            { text: "Hey! Welcome to Quacky! 🎉 Before you dive in, let's talk about what goes on your profile." },
            { text: "Your profile is public — anyone on the internet can see it. So… what info is actually safe to share?" },
        ],
        challenge: {
            type: 'choice',
            situation: "You're setting up your new Quacky profile. The form asks for your details. What should you set as publicly visible?",
            options: [
                {
                    id: 'a',
                    text: 'Full name, school, suburb, and phone number',
                    correct: false,
                    outcome: "Whoa — that's way too much! A stranger now knows exactly who you are, where you go to school, roughly where you live, and how to contact you directly. 😬",
                },
                {
                    id: 'b',
                    text: 'A username, your interests, and a profile photo',
                    correct: true,
                    outcome: "Perfect! Just enough to be social and relatable, without handing strangers personal details. That's the sweet spot. ✅",
                },
                {
                    id: 'c',
                    text: 'Full name, birthday, home address, and school grade',
                    correct: false,
                    outcome: "That's everything a predator or scammer would need to find and target you. Your address and school name should never be public. 🚫",
                },
                {
                    id: 'd',
                    text: 'Nothing at all — completely anonymous',
                    correct: false,
                    outcome: "Being anonymous is safe, but a username and interests help you connect authentically. Sharing zero info isn't necessary — just be smart about what you share.",
                },
            ],
        },
        lesson: "Keep your profile vague: a username, general interests, and a photo are plenty. Never share your real address, phone number, school name, or exact location publicly.",
        successMessage: "Nice! You know how to set up a safe profile.",
    },
    {
        id: 'privacy-2',
        worldId: 'privacy',
        number: 2,
        title: 'The Default Settings',
        subtitle: 'Are your defaults safe?',
        intro: [
            { text: "Did you know most apps ship with privacy settings that are set to share as much as possible? 😱" },
            { text: "Here are the default settings on a new Quacky account. Let's fix them." },
        ],
        challenge: {
            type: 'configure',
            platform: 'Quacky',
            context: "These are your account's default privacy settings. Fix them so your account is actually safe.",
            settings: [
                {
                    id: 'location',
                    label: 'Share my exact location publicly',
                    description: 'Anyone can see your GPS location when you post',
                    value: true,
                    correctValue: false,
                    explanation: 'Sharing your exact location means strangers can track where you are in real time. Turn this off.',
                },
                {
                    id: 'phone',
                    label: 'Show my phone number on my profile',
                    description: 'Your phone number is visible to all visitors',
                    value: true,
                    correctValue: false,
                    explanation: 'Your phone number on a public profile lets anyone contact you — including people you\'ve never met.',
                },
                {
                    id: 'dms',
                    label: 'Allow DMs from anyone',
                    description: 'Any user (including strangers) can message you',
                    value: true,
                    correctValue: false,
                    explanation: 'Allowing DMs from everyone opens you up to spam, phishing, and unwanted contact. Limit it to followers or friends.',
                },
                {
                    id: 'online',
                    label: 'Show when I\'m actively online',
                    description: 'Friends can see your "active now" status',
                    value: true,
                    correctValue: true,
                    explanation: 'Showing online status to followers/friends is generally fine and helps normal social interaction.',
                },
                {
                    id: 'search',
                    label: 'Let anyone find me by my real name',
                    description: 'Your profile appears in searches for your legal name',
                    value: true,
                    correctValue: false,
                    explanation: 'If you\'re using your real name, enabling this lets strangers search and find you. Use a username instead, or limit search to friends.',
                },
            ],
        },
        lesson: "Default app settings are almost never private-first. Always review your privacy settings when you join a new platform.",
        successMessage: "Locked and loaded! Your account is much safer now.",
    },
    {
        id: 'privacy-3',
        worldId: 'privacy',
        number: 3,
        title: 'The Overshare',
        subtitle: 'Your friend needs a heads up.',
        intro: [
            { text: "It's not just about your own posts. Your friends can accidentally put you at risk too." },
            { text: "Check this out — your friend Mia just posted something worrying." },
        ],
        challenge: {
            type: 'choice',
            situation: "You see this post from your friend Mia. What do you do?",
            post: {
                username: 'Mia Wilson',
                handle: '@mia.wilson23',
                avatar: '👧',
                content: "Home alone for the whole weekend while mum and dad are in Sydney!! Living my best life 🕺🕺 [photo: shows street sign visible in background]",
                time: '2 min ago',
                likes: 47,
                reposts: 8,
            },
            options: [
                {
                    id: 'a',
                    text: 'Like it and scroll on — not my problem',
                    correct: false,
                    outcome: "Ignoring it might feel easier, but Mia just announced she's home alone to the whole internet. A friend would speak up. 🤐",
                },
                {
                    id: 'b',
                    text: 'Send her a private DM explaining why the post is risky',
                    correct: true,
                    outcome: "Great friend move! Letting her know privately means she doesn't get embarrassed publicly — and she can take it down before it causes a problem. 💬",
                },
                {
                    id: 'c',
                    text: 'Comment: "MIA TAKE THIS DOWN you\'re home alone!!"',
                    correct: false,
                    outcome: "Oops — now even more people know the details you were trying to hide. Public comments draw more attention to the risk, not less. 😬",
                },
                {
                    id: 'd',
                    text: 'Share it to your group chat saying "lol Mia"',
                    correct: false,
                    outcome: "Spreading the post makes things much worse. More people now know Mia is home alone. That's not being a good friend.",
                },
            ],
        },
        lesson: "If a friend overshares risky information, tell them privately. Never comment publicly about risky details — that just amplifies them.",
        successMessage: "That's how you look out for a friend online. 👏",
    },
];
