services:
  upstream:
    image: ghcr.io/linusdotmy/quacky:latest
    ports:
      - "5374:3000"
    env_file: .env
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - quacky_network

  db:
    container_name: quacky-db
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: quacky
      POSTGRES_PASSWORD: quacky
      POSTGRES_DB: quacky
    volumes:
      - quacky_data:/var/lib/postgresql/data
    ports:
      - "5731:5432"

    networks:
      - quacky_network

volumes:
  quacky_data:

networks:
  quacky_network:
    driver: bridge
