apiVersion: apps/v1
kind: Deployment
metadata:
  name: quacky
  namespace: quacky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quacky
  template:
    metadata:
      labels:
        app: quacky
    spec:
      containers:
        - name: quacky
          image: ghcr.io/linuskang/quacky:latest
          ports:
            - containerPort: 5431

---
apiVersion: v1
kind: Service
metadata:
  name: quacky
  namespace: quacky
spec:
  selector:
    app: quacky
  ports:
    - port: 5431
      targetPort: 5431
  type: ClusterIP
